# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

log_level = "INFO"
domains = ["spire-oidc", "127.0.0.1", "localhost"]
allow_insecure_scheme = true
insecure_addr = "0.0.0.0:8080"
jwt_issuer = "http://spire-oidc:8080"
jwks_uri = "http://spire-oidc:8080/keys"

server_api {
    address = "unix:///run/spire/server/private/api.sock"
}

health_checks {
    bind_port = "8008"
    ready_path = "/ready"
    live_path = "/live"
}
